id: A6F42315B
base_file: fBCEA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:59:44.880672
  last_modified_at: 2022-05-31 06:59:44.880680
